project:
  type: website
output-dir: docs
website:
  title: "My-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://Ashlin-Rose-Manoj/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: spacelab
    css: styles.css



